# Site
name: 'Manjunath'
description: 'Manjunath is a profile website.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: './newtwoprofile/'
disqus: 'manjunath_kalburgi'
email: 'manjunathkalburgi65512@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration
  homepage: "pages"
  
authors:
    Manjunath:
      name:           Manjunath
      site:           https://kalburgimanjunath.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Manjunath, the author of this website,I hope you like it! you can reach me out for any website development or startup strategy consultation.Right now I'm doing consulting for various companies. I love teaching people about code, and building my own products. I use .js mainly, and I really love React, React Native, and Node.js.I'm using AWS and Vercel to deploy my products.I'm also writing a blog at my own website.I'm always available on Twitter, send me a message there too!"
      email:          manjunathkalburgi@gmail.com
      twitter:        https://twitter.com/kalburgimhubli 
    Manav:
      name:           Manav
      site:           https://manav.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Manjunath Manav, the author of this website,I hope you like it! you can reach me out for any website development or startup strategy consultation.Right now I'm doing consulting for various companies. I love teaching people about code, and building my own products. I use .js mainly, and I really love React, React Native, and Node.js.I'm using AWS and Vercel to deploy my products.I'm also writing a blog at my own website.I'm always available on Twitter, send me a message there too!"
      email:          manav@gmail.com
      twitter:        https://twitter.com/ravihubli 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Manjunath
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
